---
# Run all the playbooks in order

- name: Setup
  hosts: desktop
  gather_facts: false

- name: System
  ansible.builtin.import_playbook: playbooks/system.yml
  
- name: Fonts
  ansible.builtin.import_playbook: playbooks/fonts.yml

- name: Suckless st
  ansible.builtin.import_playbook: playbooks/st.yml

- name: Tools
  ansible.builtin.import_playbook: playbooks/tools.yml

- name: Dotfiles
  ansible.builtin.import_playbook: playbooks/dotfiles.yml

- name: Golang
  ansible.builtin.import_playbook: playbooks/go.yml
