format = """
[  ](bg:#c0caf5 fg:#294172)\
[](bg:#769ff0 fg:#c0caf5)\
$directory\
[](fg:#769ff0 bg:#ffc777)\
$git_branch\
$git_status\
[](fg:#ffc777) \
$character"""

[character] 
success_symbol = '[](#41a6b5) '
error_symbol = '[](#41a6b5) '

[directory]
style = "fg:#15161e bg:#7aa2f7 bold"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#ffc777"
format = '[[ $symbol $branch ](fg:#1f2335 bg:#ffc777 bold)]($style)'

[git_status]
style = "bg:#ffc777"
format = '[[($all_status$ahead_behind )](fg:#1f2335 bg:#ffc777)]($style)'
