---

- name: Install golang
  hosts: desktop
  tasks:
    - name: Remove old golang installations
      become: true
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: Remove old archive
      ansible.builtin.file:
        path: /tmp/go.tar.gz
        state: absent

    - name: Download go tarball
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.23.2.linux-amd64.tar.gz
        checksum: sha256:542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e
        dest: /tmp/go.tar.gz
        mode: '0755'

    - name: Extract archive
      become: true
      ansible.builtin.unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        remote_src: true
