---

- name: Install a suckless terminal that actually sucks
  hosts: desktop
  tasks:
    - name: Remove existing st repo
      become: true
      ansible.builtin.file:
        path: /usr/local/st
        state: absent

    - name: Remove existing st from tmp
      ansible.builtin.file:
        path: /tmp/st
        state: absent

    - name: Install deps
      become: true
      ansible.builtin.dnf:
        name:
          - fontconfig-devel
          - libXft-devel
        
    - name: Clone my build of st # noqa latest[git]
      ansible.builtin.git:
        repo: https://github.com/riadhlaabidi/st.git
        dest: /tmp/st
        
    - name: Move st to /usr/local # noqa no-changed-when
      become: true
      ansible.builtin.command:
        cmd: mv /tmp/st /usr/local/

    - name: Install st terminal # noqa no-changed-when
      become: true
      ansible.builtin.command:
        cmd: make clean install
        chdir: /usr/local/st
