---

- name: Basic system setup
  hosts: desktop
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest

    - name: Include locale vars
      ansible.builtin.include_vars:
        file: env.yml

    - name: Set locale # noqa no-changed-when
      ansible.builtin.command: localectl set-locale {{ system_locale }}

    - name: Set keymap # noqa no-changed-when
      ansible.builtin.command: localectl set-keymap  {{ keyboard_map }} {{ keyboard_model }} {{ keyboard_variant }}
